name: prototype_constrained_box
description: A ConstrainedBox-like widget, but the constraints are given by another widget.
version: 1.0.0
repository: https://github.com/mateusfccp/prototype_constrained_box
issue_tracker: https://github.com/mateusfccp/prototype_constrained_box/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
