# This is a basic workflow to help you get started with Actions

name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  foramtting_and_static_analysis:
    name: Formatting and static analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: dart format -l 200 --set-exit-if-changed .
    - run: flutter analyze --no-pub --no-congratulate
